### ISSUE TITLE
删除文件封装行为不符合预期

### ISSUE THREAD

**Issue by Naruto2018** [ExerciseBook/flysystem-imagex#1]
src/ImageXAdapter.php 286
 public function delete(string $path): void
    {
        $path = $this->uriPrefix . '/' . $path;
        $response = json_decode($this->client->deleteImages($this->config->serviceId, [$path]), true);
        if (isset($response["ResponseMetadata"]["Error"])) {
            throw new UnableToDeleteFile(sprintf("deleteImages: request id %s error %s", $response["ResponseMetadata"]["RequestId"], $response["ResponseMetadata"]["Error"]["Message"]));
        }
    }

这个方法 删文档 没删掉 怀疑只能删图片 ，增加个返回吧。。。

**Comment by ExerciseBook** [comment]
2023071412251358771855778E9C9B73BC

<img width="398" alt="54f76d0139d02fcf674c0dfc3a0e0ea" src="https://github.com/ExerciseBook/flysystem-imagex/assets/6327311/dd086239-f1de-4e4c-af13-3f9eaac1373c">

在文件删除成功的列表中包含不存在的文件，需要对文件删除 API 封装做修改。

**Comment by ExerciseBook** [comment]
fix in [@1.1.0](https://github.com/ExerciseBook/flysystem-imagex/tree/1.1.0)
